#!/usr/bin/env python3
"""Build the fpScreenFlip card: AutoRun.txt + fpSup.BIN, through the shared
loader (SUP_BUILD_RULES §2: build_autorun.py --loader, the product one
--boot-bin, no copy of the loader, stage2 or AutoRun generator).

One run-in-place section, called by the loader's entry chain:

    [native/launch.S][c_base: native/flip.c + uishare ui_pool.c + ui_apply.c,
     one unit, no relocation][the row's FPUI block, menu/build_flip_fpui.py]

The launcher asks the allocator for its own USER block, copies the whole
section there and calls fpf_card_init, which registers MV_fpScreenFlip (0,
memory only), adds the row to Y2_5_1 through ui_apply, and only then
subscribes the panel callback. Any failure: no row, camera stock.

The only firmware words that change are the three string sites the row's
private strings hang on (fpSup/uishare/NESTED_HOOKS.md); they are declared
with their stock words, so stage2 journals them and power-off writes them
back. The panel register and the touch flag are hardware / heap state the
firmware rebuilds at every boot.

    python3 -B build_card.py --out DIR              # dev card (USB shell in)
    python3 -B build_card.py --release --out DIR    # no shell
    python3 -B build_card.py --fs3 --out DIR        # dev card + Fast Start 3

The output directory must be new. Nothing here touches a card or the camera.
"""
import argparse
import hashlib
import json
import pathlib
import re
import shutil
import subprocess
import sys
import tempfile

HERE = pathlib.Path(__file__).resolve().parent
FPSUP = HERE.parent
ROOT = FPSUP.parent
NATIVE = HERE / 'native'
SHELL = FPSUP / 'fp_usb_shell'
sys.path.insert(0, str(FPSUP / 'uishare'))
sys.path.insert(0, str(SHELL))
sys.path.insert(0, str(ROOT / 'research/ui/tools/arm_text'))
sys.path.insert(0, str(HERE / 'menu'))

INIT = 'fpf_card_init'
UNITS = ['ui_pool.c', 'ui_apply.c', 'flip.c']
PUBLIC = re.compile(r'^(?!typedef\b|static\b|extern\b|#|enum\b|union\b|struct\s+\w+\s*\{)'
                    r'((?:USED\s+)?(?:const\s+)?(?:struct\s+\w+|u?int\w*_t|void|uintptr_t)'
                    r'\s*\**\s*(?:fpf|uis|uia)_\w+\s*\()', re.M)
# The firmware routines the launcher may call (it is assembled, so checked here).
LAUNCH_CALLS = {0xC001D740, 0xC001D7F0, 0xC000E91C, 0xC000EABC}


class CardError(RuntimeError):
    pass


def unity(tree):
    """Copies with every public fpf_/uis_/uia_ function internal (no .text
    relocation: the strict extractor refuses one), one unit including them,
    each module's private names prefixed (the uishare build_section rule)."""
    uishare = FPSUP / 'uishare'
    for src in list(NATIVE.glob('*.[ch]')) + list(uishare.glob('*.[ch]')):
        if 'fixture' in src.name:
            continue
        (tree / src.name).write_text(PUBLIC.sub(r'static \1', src.read_text()))
    lines = ['/* generated by screenflip/build_card.py */']
    for unit in UNITS:
        text = (tree / unit).read_text()
        private = sorted({n for n in re.findall(r'^static\s[^(=;]*?\b(\w+)\s*\(', text, re.M)
                          if not n.startswith(('fpf_', 'uis_', 'uia_'))})
        macros = sorted(set(re.findall(r'^\s*#\s*define\s+(\w+)', text, re.M)))
        lines += [f'#define {n} {pathlib.Path(unit).stem}__{n}' for n in private]
        lines.append(f'#include "{tree / unit}"')
        lines += [f'#undef {n}' for n in private] + [f'#undef {m}' for m in macros]
    out = tree / 'unity.c'
    out.write_text('\n'.join(lines) + '\n')
    return out


def compile_native(tmp, extra=''):
    """The unit as an object, and (unless `extra` probes it) its text."""
    import build_section
    import elf_text
    tree = pathlib.Path(tmp)
    unit = unity(tree)
    if extra:
        probe = tree / 'probe.c'
        probe.write_text(unit.read_text() + extra)
        unit = probe
    obj = tree / (unit.stem + '.o')
    clang = shutil.which('clang') or 'clang'
    r = subprocess.run([clang] + build_section.CFLAGS + ['-c', '-I', str(tree), str(unit), '-o', str(obj)],
                       capture_output=True, text=True)
    if r.returncode:
        raise CardError('compile failed:\n' + r.stderr)
    return obj, None if extra else elf_text.load_text(obj)


def probe(tmp, **exprs):
    """Compile-time constants of the unit (sizes, offsets), read back from
    the sizes of probe arrays in the object's symbol table."""
    import struct
    extra = ''.join(f'\nchar fpf_probe_{k}[{v}];' for k, v in exprs.items()) + '\n'
    obj, _ = compile_native(tmp, extra)
    d = obj.read_bytes()
    shoff, = struct.unpack_from('<I', d, 0x20)
    shentsize, shnum, _ = struct.unpack_from('<HHH', d, 0x2E)
    secs = [struct.unpack_from('<IIIIIIIIII', d, shoff + i * shentsize) for i in range(shnum)]
    symtab = next(x for x in secs if x[1] == 2)
    strtab = secs[symtab[6]]
    got = {}
    for i in range(symtab[5] // 16):
        n, _v, size, _info, _o, _s = struct.unpack_from('<IIIBBH', d, symtab[4] + 16 * i)
        name = d[strtab[4] + n:d.index(b'\0', strtab[4] + n)].decode()
        if name.startswith('fpf_probe_'):
            got[name[10:]] = size
    if set(got) != set(exprs):
        raise CardError('probe symbols missing')
    return got


def check_launcher(code):
    """Every blx in the launcher goes to an allowed firmware routine or the C."""
    from capstone import Cs, CS_ARCH_ARM, CS_MODE_ARM
    md = Cs(CS_ARCH_ARM, CS_MODE_ARM)
    lo = hi = 0
    for i in md.disasm(code, 0):
        if i.mnemonic == 'movw' and i.op_str.startswith('ip,'):
            lo = int(i.op_str.split('#')[1], 0)
        elif i.mnemonic == 'movt' and i.op_str.startswith('ip,'):
            hi = int(i.op_str.split('#')[1], 0)
        elif i.mnemonic == 'bl':
            raise CardError(f'launcher has a direct bl at {i.address:#x}')
        elif i.mnemonic == 'blx' and lo | hi << 16 >= 0xC0000000:
            if (hi << 16 | lo) not in LAUNCH_CALLS:
                raise CardError(f'launcher calls 0x{hi << 16 | lo:08X}, not an allowed routine')
            lo = hi = 0


def build_block():
    import build_flip_fpui
    from ui import fpui
    block, info, _ = build_flip_fpui.build()
    _, ops, _ = fpui.decode(block)
    if any(code == fpui.OP_HOOK_FV for code, _ in ops):
        raise CardError('the row would hook the file-redirect site: declare it first')
    return block, info


def build_blob():
    """The whole section, and the facts a test needs."""
    from armasm import assemble, symbols
    block, row = build_block()
    with tempfile.TemporaryDirectory(prefix='fpflip-') as t:
        _, text = compile_native(t)
        facts = probe(t, state='sizeof(struct fpf_card)',
                      ui_at='__builtin_offsetof(struct fpf_card, ui_at) + 1',
                      ui_len='__builtin_offsetof(struct fpf_card, ui_len) + 1')
    if (facts['ui_at'], facts['ui_len']) != (1, 5):
        raise CardError('launch.S writes ui_at/ui_len at state+0/+4; the struct moved them')
    if INIT not in text.functions or not text.functions[INIT] & 1:
        raise CardError(f'{INIT} missing or not Thumb')
    launch = NATIVE / 'launch.S'
    first = ['BLOB_LEN=0x8', 'BLOCK_BYTES=0x1000', 'STATE_OFF=0x8', 'OFF_INIT=0x1',
             'UI_OFF=0x8', 'UI_LEN=0x8']
    c_base = symbols(launch, first)['c_base']
    ui_off = c_base + len(text.code)
    ui_off += -ui_off % 8
    blob_len = ui_off + len(block)
    blob_len += -blob_len % 8
    state_off = (blob_len + 63) & ~63
    block_bytes = (state_off + facts['state'] + 0xFFF) & ~0xFFF
    defines = [f'BLOB_LEN=0x{blob_len:X}', f'BLOCK_BYTES=0x{block_bytes:X}',
               f'STATE_OFF=0x{state_off:X}', f'OFF_INIT=0x{text.functions[INIT]:X}',
               f'UI_OFF=0x{ui_off:X}', f'UI_LEN=0x{len(block):X}']
    launcher = assemble(launch, defines)
    if symbols(launch, defines)['c_base'] != c_base or len(launcher) != c_base:
        raise CardError('launch.S moved between passes')
    check_launcher(launcher)
    blob = launcher + text.code
    blob += b'\0' * (ui_off - len(blob)) + block
    blob += b'\0' * (blob_len - len(blob))
    return blob, block, {'c_base': c_base, 'c_text': len(text.code), 'ui_off': ui_off,
                         'ui_len': len(block), 'blob_len': blob_len, 'state_off': state_off,
                         'state_bytes': facts['state'], 'block_bytes': block_bytes, 'row': row,
                         'functions': {k: v for k, v in text.functions.items()
                                       if k.startswith(('fpf_', 'uia_apply'))}}


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split('\n')[0])
    ap.add_argument('--out', type=pathlib.Path, required=True, help='new directory')
    ap.add_argument('--release', action='store_true', help='no USB shell')
    ap.add_argument('--fs3', action='store_true',
                    help='Fast Start 3 (dev card): --store-boot --loader-hook --four-box-bar')
    ap.add_argument('--no-shell', action='store_true', help='with --fs3: leave the USB shell out')
    ap.add_argument('--banner', default=None)
    a = ap.parse_args(argv)
    if a.release and a.fs3:
        raise SystemExit('Fast Start 3 is for dev cards (SUP_BUILD_RULES §5)')
    if a.no_shell and not a.fs3:
        raise SystemExit('--no-shell is for --fs3 (a single card uses --release)')
    if a.out.exists():
        raise SystemExit(f'{a.out} exists: the output directory must be new')
    banner = a.banner or ('fpSup-FLIP-REL!' if a.release else 'fpSup-DEV-FLIP-FS3!' if a.fs3 else
                          'fpSup-DEV-FLIP!')
    blob, block, info = build_blob()
    tmp = pathlib.Path(tempfile.mkdtemp(prefix='fpflip-card-'))
    bf = tmp / 'screenflip.bin'
    bf.write_bytes(blob)
    a.out.mkdir(parents=True)
    cmd = [sys.executable, '-B', str(SHELL / 'build_autorun.py'), '--loader', '--banner', banner,
           '--boot-bin', f'{bf}:0', '--out', str(a.out / 'AutoRun.txt')]
    if a.release or a.no_shell:
        cmd.append('--no-shell')
    else:
        cmd.append('--no-ep-patches')
    if a.fs3:
        cmd += ['--store-boot', '--loader-hook', '--four-box-bar']
    import build_section                       # the string sites, with their stock words
    for at, word in build_section.sites(block):
        sf = tmp / f'site_{at:08X}.bin'
        sf.write_bytes(word.to_bytes(4, 'little'))
        cmd += ['--also-bin', f'0x{at:08X}:{sf}']
    r = subprocess.run(cmd, capture_output=True, text=True)
    sys.stdout.write(r.stdout)
    if r.returncode:
        sys.stderr.write(r.stderr)
        raise SystemExit('build_autorun failed')
    shutil.rmtree(tmp, ignore_errors=True)
    files = {p.name: hashlib.sha256(p.read_bytes()).hexdigest() for p in sorted(a.out.iterdir()) if p.is_file()}
    (a.out / 'screenflip.bin').write_bytes(blob)
    report = {'section': {k: v for k, v in info.items() if k != 'row'}, 'row': info['row'],
              'fpui_sha256': hashlib.sha256(block).hexdigest(),
              'command': [c if not c.startswith(str(tmp)) else pathlib.Path(c).name for c in cmd],
              'sha256': files, 'status': 'OFFLINE_ONLY_NOT_CAMERA_TESTED'}
    (a.out / 'build.json').write_text(json.dumps(report, indent=2) + '\n')
    print(f'\n  section {info["blob_len"]} B (C {info["c_text"]}, FPUI {info["ui_len"]}), resident '
          f'{info["block_bytes"]} B with state {info["state_bytes"]}')
    for name, h in files.items():
        print(f'  {name}  {h}')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
