#!/usr/bin/env python3
"""Build Loader v3: the 加載器 (\\fpSup\\LOADER.BIN), the AutoRun that loads
it, and sup files.  Design: projects/usb-shell-sup/notes/LOADER_V3.md.

    python3 v3/build_v3.py --out DIR [--sup FILE ...]

writes DIR/AutoRun.txt and DIR/fpSup/LOADER.BIN, and copies each --sup into
DIR/fpSup/.  The loader (stage 0) is the existing loader.S; only its path
changes, so it is built by build_autorun.py exactly as today and its own BIN
is thrown away.

LOADER.BIN is a VBIN with no sections: loader.S checks "VBIN" and branches to
+16 with r0 = the buffer.  What runs there is sloader_entry.S then sloader.c.
"""
import argparse, pathlib, re, shutil, struct, subprocess, sys, tempfile

HERE = pathlib.Path(__file__).resolve().parent
SHELL = HERE.parent
FPSUP = SHELL.parent
ROOT = FPSUP.parent
sys.path.insert(0, str(SHELL))
sys.path.insert(0, str(ROOT / 'research' / 'ui' / 'tools' / 'arm_text'))

import cave                                   # the cave words, one copy
from armasm import assemble, symbols

SL_DIR = 'fpSup'
SL_SELF = 'LOADER.BIN'
UI_DIR = SL_DIR + '\\UI'                    # the four-box frames: a folder, so the
                                              # 加載器's listing skips it
IMAGE = ROOT / 'out' / 'MAIN_c0000000.bin'
SL_MAGIC = 0x31425346                         # "FSB1"
SL_HEADER_LEN = 32
SL_SVC_VERSION = 3                            # sloader.h; 3 = holder, self, SL_SVC_AT
SL_SVC_AT = 0xC072F6FC                        # sloader.h: &svc while entries run, else 0

CFLAGS = ['--target=armv7a-none-eabi', '-mcpu=cortex-a9', '-mthumb', '-mfloat-abi=soft',
          '-mfpu=none', '-mstackrealign', '-ffreestanding', '-fno-builtin', '-nostdlib', '-fno-jump-tables',
          '-fropi', '-fno-addrsig', '-O2', '-std=c11', '-Wall', '-Wextra', '-Werror',
          '-Wno-unused-function']


class BuildError(RuntimeError):
    pass


def cdefs():
    return [f'-DCAVE_BUMP=0x{cave.CAVE_BUMP:08X}u', f'-DCAVE_ARENA=0x{cave.CAVE_ARENA:08X}u',
            f'-DCAVE_ARENA_END=0x{cave.CAVE_ARENA_END:08X}u',
            f'-DLOAD_DONE_US=0x{cave.LOAD_DONE_US:08X}u']


ALLSUPS_FILE = 'ALLSUPS.BIN'                  # the built-in page's data, in UI_DIR
DS_MAGIC, DS_MAX = 0x53445346, 30             # sloader.c: LOADER.BIN's disabled list
UISHARE = FPSUP / 'uishare'
PUBLIC_UI = re.compile(r'^(?!typedef\b|static\b|extern\b|#|enum\b|union\b|struct\s+\w+\s*\{)'
                       r'((?:USED\s+)?(?:const\s+)?(?:struct\s+\w+|u?int\w*_t|void|uintptr_t)'
                       r'\s*\**\s*(?:uis|uia)_\w+\s*\()', re.M)


def allsups_unity(tmp):
    """sloader.c with the built-in page (allsups.c) and the uishare it uses, as
    one unit: uishare's public functions made static (no relocations), each of
    its modules' private names prefixed and macros undone (lossless
    build_card.unity's way); sloader.c and allsups.c share one scope."""
    for src in UISHARE.glob('*.h'):
        (tmp / src.name).write_text(PUBLIC_UI.sub(r'static \1', src.read_text()))
    lines = ['/* generated by build_v3.py */']
    for path in (UISHARE / 'ui_pool.c', UISHARE / 'ui_apply.c'):
        text = PUBLIC_UI.sub(r'static \1', path.read_text())
        (tmp / path.name).write_text(text)
        private = sorted({n for n in re.findall(r'^(?:static|INLINE)\s[^(=;]*?\b(\w+)\s*\(', text, re.M)
                          if not n.startswith(('uis_', 'uia_'))})
        macros = sorted(set(re.findall(r'^\s*#\s*define\s+(\w+)', text, re.M)))
        lines += [f'#define {n} {path.stem}__{n}' for n in private]
        lines.append(f'#include "{tmp / path.name}"')
        lines += [f'#undef {n}' for n in private] + [f'#undef {m}' for m in macros]
    # the cave words come in as -D; a uishare module that defines one of them
    # (ui_pool.c's CAVE_BUMP) has just been #undef'd: put the build's back
    for d in cdefs():
        name, value = d[2:].split('=', 1)
        lines += [f'#undef {name}', f'#define {name} {value}']
    lines += [f'#include "{HERE / "sloader.c"}"', f'#include "{HERE / "allsups.c"}"']
    out = tmp / 'unity.c'
    out.write_text('\n'.join(lines) + '\n')
    return out


def compile_c(tmp, extra=(), allsups=False):
    import elf_text
    obj = tmp / 'sloader.o'
    clang = shutil.which('clang') or 'clang'
    src = allsups_unity(tmp) if allsups else HERE / 'sloader.c'
    more = ['-DSL_ALLSUPS=1', '-I', str(tmp)] if allsups else []
    r = subprocess.run([clang, *CFLAGS, *cdefs(), *extra, *more, '-c', '-I', str(HERE),
                        str(src), '-o', str(obj)], capture_output=True, text=True)
    if r.returncode:
        raise BuildError('compile failed:\n' + r.stderr)
    text = elf_text.load_text(obj)
    if not text.functions.get('sl_boot', 0) & 1:
        raise BuildError('sl_boot missing or not Thumb')
    return text


def splash_defines():
    from boot_splash import HOLD_MS, WIDTH, HEIGHT
    return ['SPLASH_FINISH=1', f'SPLASH_PATH="\\\\{SL_DIR}\\\\UI\\\\4.BIN"',
            f'SPLASH_HOLD_MS={HOLD_MS}', f'SPLASH_WIDTH_TEXT="{WIDTH}"',
            f'SPLASH_HEIGHT_TEXT="{HEIGHT}"', 'SPLASH_OFFSET_TEXT="0"']


def loader_bin(extra_cflags=(), splash=True, allsups=False):
    """(LOADER.BIN bytes, info).  `splash`: carry the four-box completion.
    `allsups`: carry the built-in SYSTEM page 6 (allsups.c; its data is
    UI_DIR\\ALLSUPS_FILE, built by fpSup/uishare/tab/build_ft6.py --data)."""
    with tempfile.TemporaryDirectory(prefix='slv3-') as t:
        text = compile_c(pathlib.Path(t), extra_cflags, allsups)
    src = HERE / 'sloader_entry.S'
    strs = [f'SL_DIR="\\\\{SL_DIR}"', f'SL_SELF="{SL_SELF}"', *(splash_defines() if splash else []),
            *([f'ALLSUPS_PATH="\\\\{SL_DIR}\\\\UI\\\\{ALLSUPS_FILE}"'] if allsups else [])]
    c_base = symbols(src, ['C_BOOT=1', *strs])['c_base']
    defines = [f'C_BOOT={c_base + text.functions["sl_boot"]}', *strs]
    stub = assemble(src, defines)
    if len(stub) != c_base or symbols(src, defines)['c_base'] != c_base:
        raise BuildError('the stub moved when the offset went in')
    code = stub + text.code
    code += b'\0' * (-len(code) % 4)
    vbin = struct.pack('<4sIII', b'VBIN', 0, 0, len(code)) + code
    if allsups:                 # the disabled list (sloader.c DS_*): empty, after the code
        vbin += struct.pack('<II', DS_MAGIC, 0) + bytes(4 * DS_MAX)
    return vbin, {'stub': len(stub), 'c_text': len(text.code), 'bytes': len(vbin),
                  'sl_boot': c_base + text.functions['sl_boot']}


def make_sup(body, entry_off, sup_id, version=1, block_size=None, min_svc=1,
             pad_to=0):
    """A sup file: the 32-byte header, then `body`.  `entry_off` is from the
    first byte of the FILE (so header + offset into body), bit 0 = Thumb.

    `pad_to`: zero-pad the file to at least this length.  The camera's open
    mode 7 overwrites without truncating, so a file written over a longer one
    keeps the old tail -- and the 加載器 refuses a header whose file_len is not
    the size on the card.  Pass the size already on the card."""
    file_len = max(SL_HEADER_LEN + len(body), pad_to)
    file_len += -file_len % 4
    block = block_size if block_size is not None else file_len
    if isinstance(sup_id, str):
        sup_id = struct.unpack('<I', sup_id.encode().ljust(4, b'\0')[:4])[0]
    hdr = struct.pack('<8I', SL_MAGIC, SL_HEADER_LEN, file_len, block, entry_off,
                      sup_id, version, min_svc)
    return (hdr + body).ljust(file_len, b'\0')


def autorun(out, extra=(), splash=True):
    """The AutoRun, from build_autorun.py --loader with the new path."""
    anim = ['--four-box-bar', '--splash-dir', UI_DIR] if splash else ['--no-four-box-bar']
    with tempfile.TemporaryDirectory(prefix='slv3ar-') as t:
        tmp = pathlib.Path(t)
        r = subprocess.run([sys.executable, '-B', str(SHELL / 'build_autorun.py'), '--loader',
                            '--no-shell', *anim,
                            '--bin-name', f'{SL_DIR}\\\\{SL_SELF}',
                            '--out', str(tmp / 'AutoRun.txt'), *extra],
                           capture_output=True, text=True)
        if r.returncode:
            raise BuildError('build_autorun failed:\n' + r.stderr + r.stdout)
        text = (tmp / 'AutoRun.txt').read_bytes()
    return text


def splash_frames():
    from boot_splash import frames
    return frames()


def stock(addr, n, image=None):
    img = image if image is not None else IMAGE.read_bytes()
    off = addr - 0xC0000000
    if not 0 <= off <= len(img) - n:
        raise BuildError(f'0x{addr:08X}: not in the reference image; give its stock bytes')
    return img[off:off + n]


def patch_sup(sup_id, rows, inner=b'', inner_entry=None, version=1, block_size=None, pad_to=0):
    """A sup made of firmware patches (patch_sup.S), optionally followed by an
    inner entry.  rows: (address, new bytes, kind) -- the stock bytes come from
    the reference image -- or (address, bytes-to-claim, kind, 'claim') to claim
    without writing (`bytes-to-claim` only gives the length), or
    (resource id, None, kind, 'res') for claim_res.
    inner_entry: offset of the entry inside `inner`."""
    img = IMAGE.read_bytes()
    src = HERE / 'patch_sup.S'
    head = len(assemble(src, ['INNER_OFF=0']))
    tbl = struct.pack('<I', len(rows))
    data = b''
    base = 4 + 20 * len(rows)
    for row in rows:
        addr, new, kind = row[:3]
        if isinstance(new, int):                    # ('res', id) style: a resource
            raise BuildError('resources are (id, None, kind, "res")')
        if len(row) > 3 and row[3] == 'res':
            tbl += struct.pack('<5I', addr, 0, kind, 0, 0)
            continue
        claim_only = len(row) > 3 and row[3] == 'claim'
        n = len(new)
        if n % 4 or addr % 4 or not n:
            raise BuildError(f'0x{addr:08X}: patches are whole words')
        old = stock(addr, n, img)
        so = base + len(data)
        data += old
        if claim_only:
            no = 0
        else:
            no = base + len(data)
            data += new
        tbl += struct.pack('<5I', addr, n, kind, so, no)
    tabled = tbl + data
    inner_off = 0 if inner_entry is None else head + len(tabled) + inner_entry
    code = assemble(src, [f'INNER_OFF={inner_off}'])
    if len(code) != head:
        raise BuildError('patch_sup.S moved when the offset went in')
    return make_sup(code + tabled + inner, SL_HEADER_LEN, sup_id, version, block_size,
                    pad_to=pad_to)


def shell_sup(ep_patches=False, pad_to=0, burst15=False, noptp=True):
    """The USB shell: worker.S's `spawn`, after the rendezvous block is zeroed and
    the interface patch is in -- the two things pass 1 used to place."""
    import patches
    worker = SHELL / 'camera' / 'worker.S'
    code = assemble(worker)
    m = re.search(r'^\.equ\s+STATE,\s*(0x[0-9A-Fa-f]+)', worker.read_text(), re.M)
    if not m:
        raise BuildError('worker.S: no STATE')
    # The worker's 96 rendezvous bytes, zero.  The cave survives a warm restart;
    # a stale 'VSHL' at +0 would make spawn think a worker is already running.
    rows = [(int(m.group(1), 16), b'\0' * 96, 2)]
    rows += [(a, struct.pack('<I', v), 2) for a, v, *_ in patches.IFACE]
    if ep_patches:
        rows += [(a, struct.pack('<I', v), 2) for a, v, *_ in patches.PUSH]
    if burst15:
        rows += [(a, struct.pack('<I', v), 2) for a, v, *_ in patches.BURST15]
    if noptp:      # the firmware's PTP receiver steals shell commands (patches.py)
        rows += [(a, struct.pack('<I', v), 2) for a, v, *_ in patches.NOPTP]
    return patch_sup('SHEL', rows, code, symbols(worker)['spawn'], pad_to=pad_to)


def loader_words(autorun_text):
    """The loader as the AutoRun spells it out: {address: word}."""
    sets = re.findall(rb'^mem set (0x[0-9A-Fa-f]+) (0x[0-9A-Fa-f]+)', autorun_text, re.M)
    lo = cave.CAVE_ARENA - 0x200
    return {int(a, 16): int(v, 16) for a, v in sets if lo <= int(a, 16) < cave.CAVE_ARENA}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--out', type=pathlib.Path, required=True)
    ap.add_argument('--sup', action='append', default=[], type=pathlib.Path)
    ap.add_argument('--shell', action='store_true', help='add the USB shell as 00SHELL.BIN')
    ap.add_argument('--no-splash', action='store_true')
    a = ap.parse_args()
    vbin, info = loader_bin(splash=not a.no_splash)
    d = a.out / SL_DIR
    d.mkdir(parents=True, exist_ok=True)
    (d / SL_SELF).write_bytes(vbin)
    (a.out / 'AutoRun.txt').write_bytes(autorun(a.out, splash=not a.no_splash))
    if not a.no_splash:
        (d / 'UI').mkdir(exist_ok=True)
        for i, px in enumerate(splash_frames()):
            (d / 'UI' / f'{i}.BIN').write_bytes(px)
    if a.shell:
        (d / '00SHELL.BIN').write_bytes(shell_sup())
    for s in a.sup:
        shutil.copy(s, d / s.name.upper())
    print(info)


if __name__ == '__main__':
    main()
