#!/usr/bin/env python3
"""Build fpScreenFlip as a Loader v3 sup: \\fpSup\\40FLIP.BIN.

    python3 -B screenflip/build_v3_flip.py --out /absolute/new/directory [--card]

Design: projects/usb-shell-sup/notes/LOADER_V3.md; behaviour: native/flip.h.
The file IS the block:

    [FSB1 header][native/entry.S][c_base: flip.c + uishare ui_pool.c/ui_apply.c,
     one unit, no relocation][the row's FPUI block][zeroed: struct fpf_card]

entry(block, svc, path) claims the panel register and the touch flag (EXCL
resources) and the three uishare string-layer sites the row's strings hang on
(SHARED_UI, journaled, put back at power-off), then fpf_card_init registers
MV_fpScreenFlip, adds the row, subscribes and starts the task.

The flip value of each custom is entry.S `settings`, inside this file: the
task rewrites it in place, so the sup's own file is its settings store.

--out DIR writes DIR/40FLIP.BIN and build.json. --card makes DIR a whole v3
card (AutoRun.txt, fpSup/LOADER.BIN, fpSup/UI/, fpSup/00SHELL.BIN unless
--no-shell, fpSup/40FLIP.BIN, MANIFEST.sha256). It never writes a camera card.
"""
import argparse
import hashlib
import json
import pathlib
import re
import shutil
import struct
import subprocess
import sys
import tempfile

HERE = pathlib.Path(__file__).resolve().parent
FPSUP = HERE.parent
ROOT = FPSUP.parent
NATIVE = HERE / 'native'
V3 = FPSUP / 'fp_usb_shell' / 'v3'
sys.path.insert(0, str(FPSUP / 'uishare'))
sys.path.insert(0, str(FPSUP / 'fp_usb_shell'))
sys.path.insert(0, str(V3))
sys.path.insert(0, str(ROOT / 'research/ui/tools/arm_text'))
sys.path.insert(0, str(HERE / 'menu'))

import build_v3 as B                                     # noqa: E402

NAME = '40FLIP.BIN'
SUP_ID = 'FLIP'
VERSION = 1
UNITS = ['ui_pool.c', 'ui_apply.c', 'flip.c']
ENTRIES = {'OFF_INIT': 'fpf_card_init', 'OFF_TASK': 'fpf_task', 'OFF_CHANGED': 'fpf_changed'}
PUBLIC = re.compile(r'^(?!typedef\b|static\b|extern\b|#|enum\b|union\b|struct\s+\w+\s*\{)'
                    r'((?:USED\s+)?(?:const\s+)?(?:struct\s+\w+|u?int\w*_t|void|uintptr_t)'
                    r'\s*\**\s*(?:fpf|uis|uia)_\w+\s*\()', re.M)
# Every absolute address entry.S may call or claim (it is assembled, so checked here).
ENTRY_CALLS = {0xC000E91C}
CLAIMED = {0x30190044, 0xC3760E44}


class BuildError(RuntimeError):
    pass


def unity(tree):
    """Copies with every public fpf_/uis_/uia_ function internal (no .text
    relocation: the strict extractor refuses one), one unit including them,
    each module's private names prefixed (the uishare build_section rule)."""
    uishare = FPSUP / 'uishare'
    for src in list(NATIVE.glob('*.[ch]')) + list(uishare.glob('*.[ch]')):
        if 'fixture' in src.name:
            continue
        (tree / src.name).write_text(PUBLIC.sub(r'static \1', src.read_text()))
    lines = ['/* generated by screenflip/build_v3_flip.py */']
    for unit in UNITS:
        text = (tree / unit).read_text()
        private = sorted({n for n in re.findall(r'^static\s[^(=;]*?\b(\w+)\s*\(', text, re.M)
                          if not n.startswith(('fpf_', 'uis_', 'uia_'))})
        macros = sorted(set(re.findall(r'^\s*#\s*define\s+(\w+)', text, re.M)))
        lines += [f'#define {n} {pathlib.Path(unit).stem}__{n}' for n in private]
        lines.append(f'#include "{tree / unit}"')
        lines += [f'#undef {n}' for n in private] + [f'#undef {m}' for m in macros]
    out = tree / 'unity.c'
    out.write_text('\n'.join(lines) + '\n')
    return out


def compile_unit(tree, settings_off, extra=''):
    import build_section
    unit = tree / 'unity.c'
    if extra:
        unit = tree / 'probe.c'
        unit.write_text((tree / 'unity.c').read_text() + extra)
    obj = tree / (unit.stem + '.o')
    clang = shutil.which('clang') or 'clang'
    r = subprocess.run([clang] + build_section.CFLAGS + [f'-DFPF_SETTINGS_OFF=0x{settings_off:X}u',
                        '-c', '-I', str(tree), str(unit), '-o', str(obj)],
                       capture_output=True, text=True)
    if r.returncode:
        raise BuildError('compile failed:\n' + r.stderr)
    return obj


def symbol_sizes(obj, prefix):
    d = obj.read_bytes()
    shoff, = struct.unpack_from('<I', d, 0x20)
    shentsize, shnum, _ = struct.unpack_from('<HHH', d, 0x2E)
    secs = [struct.unpack_from('<IIIIIIIIII', d, shoff + i * shentsize) for i in range(shnum)]
    symtab = next(x for x in secs if x[1] == 2)
    strtab = secs[symtab[6]]
    got = {}
    for i in range(symtab[5] // 16):
        n, _v, size, _info, _o, _s = struct.unpack_from('<IIIBBH', d, symtab[4] + 16 * i)
        name = d[strtab[4] + n:d.index(b'\0', strtab[4] + n)].decode()
        if name.startswith(prefix):
            got[name[len(prefix):]] = size
    return got


def check_entry(code):
    """entry.S: every absolute address it builds is a routine it may call or a
    resource it claims; no direct bl out of the block."""
    from capstone import Cs, CS_ARCH_ARM, CS_MODE_ARM
    md = Cs(CS_ARCH_ARM, CS_MODE_ARM)
    lo = {}
    for i in md.disasm(code, 0):
        if i.mnemonic == 'bl':
            raise BuildError(f'entry.S has a direct bl at {i.address:#x}')
        if i.mnemonic in ('movw', 'movt'):
            reg, imm = i.op_str.split(', #')
            imm = int(imm, 0)
            if i.mnemonic == 'movw':
                lo[reg] = imm
            else:
                full = lo.pop(reg, 0) | imm << 16
                if full >= 0x30000000 and full not in ENTRY_CALLS | CLAIMED:
                    raise BuildError(f'entry.S names 0x{full:08X}')


def check_claims(code, at, block):
    """entry.S `claims`: exactly the words the row's block makes ui_apply
    change (uishare build_section.sites), each with the reference image's
    stock word, SHARED_UI."""
    import build_section
    n, = struct.unpack_from('<I', code, at)
    rows = [struct.unpack_from('<3I', code, at + 4 + 12 * i) for i in range(n)]
    img = B.IMAGE.read_bytes()
    want = build_section.sites(block)
    if sorted((a, s) for a, s, _ in rows) != sorted(want):
        raise BuildError(f'entry.S claims {rows} are not the block\'s sites {want}')
    for a, s, k in rows:
        if B.stock(a, 4, img) != struct.pack('<I', s) or k != 3:
            raise BuildError(f'0x{a:08X}: stock 0x{s:08X} / kind {k}')
    return rows


def menu_block():
    import build_flip_fpui
    from ui import fpui
    block, info, _ = build_flip_fpui.build()
    _, ops, _ = fpui.decode(block)
    if any(code == fpui.OP_HOOK_FV for code, _ in ops):
        raise BuildError('the row would hook the file redirect: claim it first')
    return block, info


def build_blob():
    """The blob (the file after its header) and the facts a test needs."""
    from armasm import assemble, symbols
    import elf_text
    block, row = menu_block()
    src = NATIVE / 'entry.S'
    probe_defs = ['STATE_OFF=0x8', 'UI_OFF=0x8', 'UI_LEN=0x8'] + [f'{k}=0x1' for k in ENTRIES]
    first = symbols(src, probe_defs)
    c_base, settings_off = first['c_base'], first['settings']
    with tempfile.TemporaryDirectory(prefix='fpflip-v3-') as t:
        tree = pathlib.Path(t)
        unity(tree)
        text = elf_text.load_text(compile_unit(tree, settings_off))
        fields = ['ui_at', 'ui_len', 'task_entry', 'changed_entry', 'magic', 'table', 'saved',
                  'settings_ok', 'live_key', 'edit_key', 'last_apply', 'polls', 'switches',
                  'applies', 'refused', 'pushes', 'edits', 'saves', 'save_failed', 'name',
                  'result', 'task_id', 'self_path', 'registered', 'subscribe_result',
                  'ui_result', 'page', 'row_y']
        extra = '\nchar fpf_size_state[sizeof(struct fpf_card)];\n' + ''.join(
            f'char fpf_off_{f}[__builtin_offsetof(struct fpf_card, {f}) + 1];\n' for f in fields)
        sizes = symbol_sizes(compile_unit(tree, settings_off, extra), 'fpf_')
    layout = {f: sizes[f'off_{f}'] - 1 for f in fields}
    if [layout[f] for f in ('ui_at', 'ui_len', 'task_entry', 'changed_entry')] != [0, 4, 8, 12]:
        raise BuildError('entry.S fills state+0..+12; the struct moved them')
    for k, fn in ENTRIES.items():
        if not text.functions.get(fn, 0) & 1:
            raise BuildError(f'{fn} missing or not Thumb')
    ui_off = (c_base + len(text.code) + 7) & ~7
    blob_len = (ui_off + len(block) + 7) & ~7
    state_off = (blob_len + 63) & ~63
    block_bytes = (state_off + sizes['size_state'] + 0xFFF) & ~0xFFF
    defines = [f'STATE_OFF=0x{state_off:X}', f'UI_OFF=0x{ui_off:X}', f'UI_LEN=0x{len(block):X}'] + \
              [f'{k}=0x{text.functions[v]:X}' for k, v in ENTRIES.items()]
    code = assemble(src, defines)
    syms = symbols(src, defines)
    if syms['c_base'] != c_base or len(code) != c_base or syms['settings'] != settings_off:
        raise BuildError('entry.S moved between passes')
    check_entry(code[:syms['g_state']])
    check_claims(code, syms['claims'], block)
    blob = code + text.code
    blob += b'\0' * (ui_off - len(blob)) + block
    blob += b'\0' * (blob_len - len(blob))
    return blob, {'c_base': c_base, 'c_text': len(text.code), 'ui_off': ui_off,
                  'ui_len': len(block), 'blob_len': blob_len, 'state_off': state_off,
                  'state_bytes': sizes['size_state'], 'block_bytes': block_bytes,
                  'settings_off': settings_off, 'row': row, 'defines': defines,
                  'layout': layout, 'symbols': {k: syms[k] for k in
                                                ('entry', 'task_shim', 'changed_shim', 'g_state',
                                                 'w_task', 'w_changed', 'settings', 'claims',
                                                 'c_base')},
                  'functions': {k: v for k, v in text.functions.items() if k.startswith('fpf_')}}


def sup_file(pad_to=0):
    blob, facts = build_blob()
    # min_svc 2: entry needs its own path in r2 to save the table
    data = B.make_sup(blob, B.SL_HEADER_LEN, SUP_ID, VERSION,
                      block_size=B.SL_HEADER_LEN + facts['block_bytes'], min_svc=2, pad_to=pad_to)
    return data, facts


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split('\n')[0])
    ap.add_argument('--out', type=pathlib.Path, required=True)
    ap.add_argument('--card', action='store_true',
                    help='a whole v3 card: loader, AutoRun, frames, shell and screenflip')
    ap.add_argument('--no-shell', action='store_true', help='with --card: leave 00SHELL.BIN out')
    a = ap.parse_args(argv)
    out = a.out.resolve()
    if out.exists() and any(out.iterdir()):
        raise SystemExit(f'{out} is not empty: this never overwrites a build or a card')
    out.mkdir(parents=True, exist_ok=True)
    data, facts = sup_file()
    if a.card:
        vbin, _ = B.loader_bin()
        d = out / B.SL_DIR
        (d / 'UI').mkdir(parents=True)
        (d / B.SL_SELF).write_bytes(vbin)
        (out / 'AutoRun.txt').write_bytes(B.autorun(out))
        for i, px in enumerate(B.splash_frames()):
            (d / 'UI' / f'{i}.BIN').write_bytes(px)
        if not a.no_shell:
            (d / '00SHELL.BIN').write_bytes(B.shell_sup(burst15=True))
        (d / NAME).write_bytes(data)
    else:
        (out / NAME).write_bytes(data)
    sources = [pathlib.Path(__file__), NATIVE / 'entry.S', NATIVE / 'flip.c', NATIVE / 'flip.h',
               *sorted(p for p in (FPSUP / 'uishare').glob('*.[chS]') if 'fixture' not in p.name),
               HERE / 'menu' / 'build_flip_page.py', HERE / 'menu' / 'build_flip_fpui.py']
    (out / 'build.json').write_text(json.dumps({
        'product': 'fpScreenFlip, Loader v3 sup', 'file': NAME, 'sup_id': SUP_ID,
        'version': VERSION, 'card': a.card,
        'blob': {k: v for k, v in facts.items() if k not in ('row', 'defines')},
        'row': facts['row'], 'sha256': hashlib.sha256(data).hexdigest(),
        'sources': {str(p.relative_to(ROOT)): hashlib.sha256(p.read_bytes()).hexdigest()
                    for p in sources},
        'written_to_card': False, 'camera_tested': False}, indent=1) + '\n')
    if a.card:
        files = sorted(p for p in out.rglob('*') if p.is_file() and p.name != 'MANIFEST.sha256')
        (out / 'MANIFEST.sha256').write_text(''.join(
            f'{hashlib.sha256(p.read_bytes()).hexdigest()}  ./{p.relative_to(out)}\n'
            for p in files))
    print(f'built into {out}')
    print(json.dumps({k: facts[k] for k in ('c_text', 'ui_len', 'blob_len', 'state_off',
                                             'state_bytes', 'block_bytes', 'settings_off')}))
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
