#!/usr/bin/env python3
"""A sup's FPUI block as a ready section: the shared applier with the block.

    from build_section import section
    blob, info = section(fpui_bytes)
    # then: build_autorun ... --boot-bin FILE:0, and declare info['sites']
    #       (each as a 4-byte --also-bin holding the firmware's own word)

The section is section.S, then ui_pool.c + ui_apply.c compiled as one unit
with every call resolved by the compiler (no relocations: the strict text
extractor refuses anything else), then the block. Any sup, whatever its own
code is written in, carries its UI additions this way; the loader's entry
chain runs it like any other run-in-place entry.

info['sites'] lists the firmware words the block may change at run time
(the file-redirect site, when the block hooks it): the card must declare
each with its stock word so stage2 journals it and the power-off callback
writes it back (SUP_BUILD_RULES §4).
"""
import pathlib
import re
import shutil
import struct
import subprocess
import sys
import tempfile

HERE = pathlib.Path(__file__).resolve().parent
FPSUP = HERE.parent
ROOT = FPSUP.parent
sys.path.insert(0, str(FPSUP / 'fp_usb_shell'))
sys.path.insert(0, str(ROOT / 'research' / 'ui' / 'tools' / 'arm_text'))
sys.path.insert(0, str(HERE))

CFLAGS = ['--target=armv7a-none-eabi', '-mcpu=cortex-a9', '-mthumb', '-mfloat-abi=soft',
          '-mfpu=none', '-ffreestanding', '-fno-builtin', '-nostdlib', '-fno-jump-tables',
          '-fropi', '-fno-addrsig', '-O2', '-std=c11', '-Wall', '-Wextra', '-Werror',
          '-Wno-unused-function']
UNITS = ['ui_pool.c', 'ui_apply.c']
PUBLIC = re.compile(r'^((?:const\s+)?(?:struct\s+\w+|u?int\w*_t|void|uintptr_t)'
                    r'\s*\**\s*(?:uis|uia)_\w+\s*\()', re.M)


class SectionError(RuntimeError):
    pass


def unity(tree):
    """Copies with the public functions made internal, one unit including
    them, each unit's private names prefixed so two can share a name."""
    for src in list(HERE.glob('*.[ch]')):
        if 'fixture' in src.name:
            continue
        (tree / src.name).write_text(PUBLIC.sub(r'static \1', src.read_text()))
    lines = ['/* generated by build_section.py */']
    for unit in UNITS:
        text = (tree / unit).read_text()
        private = sorted({s for s in re.findall(r'^static\s[^(=;]*?\b(\w+)\s*\(', text, re.M)
                          if not s.startswith(('uis_', 'uia_'))})
        macros = sorted(set(re.findall(r'^\s*#\s*define\s+(\w+)', text, re.M)))
        lines += [f'#define {s} {pathlib.Path(unit).stem}__{s}' for s in private]
        lines.append(f'#include "{tree / unit}"')
        lines += [f'#undef {s}' for s in private] + [f'#undef {m}' for m in macros]
    lines.append('void *uia_section_keep(void) { return (void *)uia_apply; }')
    out = tree / 'unity.c'
    out.write_text('\n'.join(lines) + '\n')
    return out


def compile_text(tmp):
    import elf_text
    tree = tmp / 'tree'
    tree.mkdir()
    unit = unity(tree)
    obj = tmp / 'unity.o'
    clang = shutil.which('clang') or 'clang'
    r = subprocess.run([clang] + CFLAGS + ['-c', '-I', str(tree), str(unit), '-o', str(obj)],
                       capture_output=True, text=True)
    if r.returncode:
        raise SectionError('compile failed:\n' + r.stderr)
    text = elf_text.load_text(obj)
    if 'uia_apply' not in text.functions or not text.functions['uia_apply'] & 1:
        raise SectionError('uia_apply missing or not Thumb')
    return text


def sites(block):
    """The firmware words a block may change at run time: (address, stock word)."""
    from ui import fpui
    _, ops, _ = fpui.decode(block)
    return sorted({(a[0], a[1]) for code, a in ops if code == fpui.OP_HOOK_FV})


def section(block):
    from armasm import assemble, symbols
    with tempfile.TemporaryDirectory(prefix='uisec-') as t:
        tmp = pathlib.Path(t)
        text = compile_text(tmp)
        src = HERE / 'section.S'
        probe = ['BLOCK_OFF=0', 'BLOCK_LEN=0', 'OFF_APPLY=1']
        c_base = symbols(src, probe)['c_base']
        code_len = c_base + len(text.code)
        block_off = (code_len + 3) & ~3
        defines = [f'BLOCK_OFF={block_off}', f'BLOCK_LEN={len(block)}',
                   f'OFF_APPLY={c_base + text.functions["uia_apply"]}']
        stub = assemble(src, defines)
        if symbols(src, defines)['c_base'] != c_base or len(stub) != c_base:
            raise SectionError('the entry moved when the offsets went in')
        blob = stub + text.code + b'\0' * (block_off - code_len) + block
        blob += b'\0' * (-len(blob) % 4)
    return blob, {'c_base': c_base, 'c_text': len(text.code), 'block_off': block_off,
                  'block_len': len(block), 'bytes': len(blob), 'sites': sites(block),
                  'uia_apply': c_base + text.functions['uia_apply']}


if __name__ == '__main__':
    data = pathlib.Path(sys.argv[1]).read_bytes()
    blob, info = section(data)
    pathlib.Path(sys.argv[2]).write_bytes(blob)
    print(info)
