#!/usr/bin/env python3
"""ui_strings.S -> ui_strings_code.h (the words ui_pool.c writes for a layer).

The camera build of ui_pool.c may have no .rodata and no relocations, so the
layer's code is not a table: it is a function that stores each word with an
immediate. Run after changing ui_strings.S; test_ui_strings.py fails while the
header is stale.

    python3 -B gen_strings_code.py          # rewrite the header
    python3 -B gen_strings_code.py --check  # exit 1 if it is stale
"""
import pathlib
import struct
import sys

HERE = pathlib.Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent / 'fp_usb_shell'))
SOURCE = HERE / 'ui_strings.S'
HEADER = HERE / 'ui_strings_code.h'
HEADER_BYTES = 72                       # ui_strings.S hdr: eighteen words, filled by ui_pool.c


def layer():
    """(code bytes, {symbol: offset}) of one layer."""
    from armasm import assemble, symbols
    code = assemble(SOURCE)
    syms = symbols(SOURCE)
    if syms['hdr'] != 0 or syms['resolve'] != HEADER_BYTES + 4 or syms['layer_end'] != len(code):
        raise SystemExit('ui_strings.S layout is not [header %d B][back word][code]' % HEADER_BYTES)
    for e in ('resolve', 'owns', 'remain'):            # each entry is preceded by its own offset
        if struct.unpack_from('<I', code, syms[e] - 4)[0] != syms[e]:
            raise SystemExit('ui_strings.S: the word before %s is not its offset' % e)
    if any(code[:HEADER_BYTES]):
        raise SystemExit('the header must assemble to zeros')
    return code, syms


def render():
    code, syms = layer()
    words = struct.unpack('<%dI' % (len(code) // 4), code)
    lines = ['/* generated by gen_strings_code.py from ui_strings.S -- do not edit */',
             '#define UIS_LAYER_BYTES   %du' % len(code),
             '#define UIS_LAYER_RESOLVE %du' % syms['resolve'],
             '#define UIS_LAYER_OWNS    %du' % syms['owns'],
             '#define UIS_LAYER_REMAIN  %du' % syms['remain'],
             '#define UIS_LAYER_HEADER  %du' % HEADER_BYTES,
             '',
             '/* The layer\'s code after its %d-byte header (which the caller fills). */' % HEADER_BYTES,
             'static void uis_layer_code(uintptr_t at) {']
    for i in range(HEADER_BYTES // 4, len(words)):
        lines.append('    poke(at + %3du, 0x%08Xu);' % (4 * i, words[i]))
    lines += ['}', '']
    return '\n'.join(lines)


if __name__ == '__main__':
    text = render()
    if '--check' in sys.argv[1:]:
        sys.exit(0 if HEADER.exists() and HEADER.read_text() == text else 1)
    HEADER.write_text(text)
    print('wrote', HEADER.name)
