#!/usr/bin/env python3
"""The Quick Set record layer as bytes a sup puts in its block (QS_SHARE.md §2).

    blob, sym = qs_build.layer_blob()

blob = [qs_layer.S: header (64 B), entry, qs_replay][qs_apply.c + qs_layer.c,
Thumb, -fropi, one unit, no relocation][the recipe table (ui/qs.py encode)].
sym: offsets in blob -- 'header', 'entry', 'replay', 'table', and the C
functions ('qs_check', 'qs_hang', 'qs_record', 'qs_rows_now', +1 = Thumb).
The sup's entry calls qs_check (before it claims), then qs_hang (commit).
"""
import pathlib
import struct
import re
import shutil
import subprocess
import sys
import tempfile

HERE = pathlib.Path(__file__).resolve().parent
FPSUP = HERE.parent
ROOT = FPSUP.parent
sys.path.insert(0, str(FPSUP / 'fp_usb_shell'))
sys.path.insert(0, str(ROOT / 'research' / 'ui' / 'tools' / 'arm_text'))
sys.path.insert(0, str(HERE))

CFLAGS = ['--target=armv7a-none-eabi', '-mcpu=cortex-a9', '-mthumb', '-mfloat-abi=soft',
          '-mfpu=none', '-ffreestanding', '-fno-builtin', '-nostdlib', '-fno-jump-tables',
          '-fropi', '-fno-addrsig', '-O2', '-std=c11', '-Wall', '-Wextra', '-Werror',
          '-Wno-unused-function',
          # every frame 8-aligned, leaf functions too (clang leaves a leaf's frame
          # 4-aligned otherwise; memory arm-stack-alignment, test_stack_alignment.py)
          '-mstackrealign']
UNITS = ['qs_apply.c', 'qs_layer.c']
PUBLIC = re.compile(r'^((?:const\s+)?(?:struct\s+\w+|u?int\w*_t|void|uintptr_t)'
                    r'\s*\**\s*qs_\w+\s*\()', re.M)
KEEP = ('qs_check', 'qs_hang', 'qs_record', 'qs_rows_now', 'qs_layout', 'qs_load', 'qs_pack_place')


class QsBuildError(RuntimeError):
    pass


def _unity(tree, edits=()):
    for name in ['qs_apply.c', 'qs_apply.h', 'qs_layer.c', 'qs_layer.h']:
        text = (HERE / name).read_text()
        for file, old, new in edits:                  # tests: a mutated build
            if file == name:
                if text.count(old) != 1:
                    raise QsBuildError(f'{name}: edit not found once: {old!r}')
                text = text.replace(old, new)
        (tree / name).write_text(PUBLIC.sub(r'static \1', text))
    lines = ['/* generated by qs_build.py */']
    lines += [f'#include "{tree / u}"' for u in UNITS]
    lines.append('void *qs_keep(uint32_t i) {' +
                 ''.join(f' if (i == {n}) return (void *){k};' for n, k in enumerate(KEEP)) +
                 ' return 0; }')
    out = tree / 'unity.c'
    out.write_text('\n'.join(lines) + '\n')
    return out


def c_text(defines=(), edits=()):
    import elf_text
    with tempfile.TemporaryDirectory(prefix='qsb-') as t:
        tree = pathlib.Path(t)
        unit = _unity(tree, edits)
        obj = tree / 'unity.o'
        r = subprocess.run([shutil.which('clang') or 'clang', *CFLAGS, *defines, '-c', '-I', str(tree),
                            str(unit), '-o', str(obj)], capture_output=True, text=True)
        if r.returncode:
            raise QsBuildError('compile failed:\n' + r.stderr)
        return elf_text.load_text(obj)


def layer_blob(table=None, source=None, edits=()):
    """`source`: another qs_layer.S (tests: a build whose entries moved).
    `edits`: (file, old, new) applied to the C sources (tests: mutations)."""
    from armasm import assemble, symbols
    from ui import qs
    src = source or HERE / 'qs_layer.S'
    head = assemble(src)
    s = symbols(src)
    want = ('qs_entry_record', 'qs_entry_layout', 'qs_entry_load',
            'qs_replay_record', 'qs_replay_layout', 'qs_replay_load')
    # the offsets this build's C needs, from the assembly itself
    defines = [f'-D{k.upper()}={(s[k] & ~1)}u' for k in want]
    for k, f in (('qs_entry_record', 164), ('qs_entry_layout', 168), ('qs_entry_load', 172)):
        if struct.unpack_from('<I', head, f)[0] != s[k] or struct.unpack_from('<I', head, s[k] - 4)[0] != s[k]:
            raise QsBuildError(f'qs_layer.S: {k} is not described by its header / back word')
    text = c_text(defines, edits)
    c_base = len(head) + (-len(head) % 8)
    blob = head + bytes(c_base - len(head)) + text.code
    blob += bytes(-len(blob) % 8)
    table_off = len(blob)
    blob += table if table is not None else qs.encode()
    sym = {'header': 0, 'table': table_off, **{k: s[k] for k in want}}
    for k in KEEP:
        sym[k] = c_base + text.functions[k]
    return blob, sym
